name: Foo
height: 12
width: 23
weight: 14.5
certified: true
reserved: false
colors:
  - red
  - blue
  - black
numbers:
  - 1
  - 45
  - 695
moreNumbers:
  - 1.34
  - 11.2
  - 31.45
booleans:
  - true
  - false
  - false
nested:
  name: Bar
  weight: 45.6
  certified: true
